# Generated by Django 3.0.4 on 2020-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_subject', models.CharField(choices=[('City', 'ในเมือง'), ('Suburb', 'นอกเขตเมือง')], default='city', max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_id', models.IntegerField(default=0)),
            ],
        ),
    ]
